package it.eng.eli4u.imieidati.services.database.entities;

// Generated il giorno 31-lug-2014 11.28.28 by Hibernate Tools 3.4.0.CR1

/**
 * Localizzazione generated by hbm2java
 */
public class Localizzazione implements java.io.Serializable {

	private double idLocalizz;
	private String chiave;
	private String locale;
	private String valore;

	public Localizzazione() {
	}

	public Localizzazione(double idLocalizz, String chiave, String locale,
			String valore) {
		this.idLocalizz = idLocalizz;
		this.chiave = chiave;
		this.locale = locale;
		this.valore = valore;
	}

	public double getIdLocalizz() {
		return this.idLocalizz;
	}

	public void setIdLocalizz(double idLocalizz) {
		this.idLocalizz = idLocalizz;
	}

	public String getChiave() {
		return this.chiave;
	}

	public void setChiave(String chiave) {
		this.chiave = chiave;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public String getValore() {
		return this.valore;
	}

	public void setValore(String valore) {
		this.valore = valore;
	}

}
