package it.eng.eli4u.imieidati.services.database.entities;

// Generated il giorno 31-lug-2014 11.28.28 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Sezione generated by hbm2java
 */
public class Sezione implements java.io.Serializable {

	private double id;
	private String codice;
	private String titolo;
	private String descrizione;
	private String image;
	private String uriXsl;
	private String uriXslMobile;
	private String datiXsl;
	private String datiXslMobile;
	private String htmlStatico;
	private short flgAbilitato;
	private String idServizio;
	private String urlServizio;
	private String nomeServizio;
	private String usernameServizio;
	private String passwordeServizio;
	private String portletAbilitate;
	private String renderingClass;
	
	private Set<ParametroServizio> parametroServizios = new HashSet<ParametroServizio>(
			0);

	public Sezione() {
	}

	public Sezione(double id, String codice, String titolo, short flgAbilitato) {
		this.id = id;
		this.codice = codice;
		this.titolo = titolo;
		this.flgAbilitato = flgAbilitato;
	}

	public Sezione(double id, String codice, String titolo, String descrizione,
			String image, String uriXsl, String uriXslMobile, String datiXsl,
			String datiXslMobile, String htmlStatico, short flgAbilitato,
			String idServizio, String urlServizio, String nomeServizio,
			String usernameServizio, String passwordeServizio,
			Set<ParametroServizio> parametroServizios, String portletAbilitate, String renderingClass) {
		this.id = id;
		this.codice = codice;
		this.titolo = titolo;
		this.descrizione = descrizione;
		this.image = image;
		this.uriXsl = uriXsl;
		this.uriXslMobile = uriXslMobile;
		this.datiXsl = datiXsl;
		this.datiXslMobile = datiXslMobile;
		this.htmlStatico = htmlStatico;
		this.flgAbilitato = flgAbilitato;
		this.idServizio = idServizio;
		this.urlServizio = urlServizio;
		this.nomeServizio = nomeServizio;
		this.usernameServizio = usernameServizio;
		this.passwordeServizio = passwordeServizio;
		this.parametroServizios = parametroServizios;
		this.portletAbilitate = portletAbilitate;
		this.renderingClass = renderingClass;
	}

	public double getId() {
		return this.id;
	}

	public void setId(double id) {
		this.id = id;
	}

	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	public String getTitolo() {
		return this.titolo;
	}

	public void setTitolo(String titolo) {
		this.titolo = titolo;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getUriXsl() {
		return this.uriXsl;
	}

	public void setUriXsl(String uriXsl) {
		this.uriXsl = uriXsl;
	}

	public String getUriXslMobile() {
		return this.uriXslMobile;
	}

	public void setUriXslMobile(String uriXslMobile) {
		this.uriXslMobile = uriXslMobile;
	}

	public String getDatiXsl() {
		return this.datiXsl;
	}

	public void setDatiXsl(String datiXsl) {
		this.datiXsl = datiXsl;
	}

	public String getDatiXslMobile() {
		return this.datiXslMobile;
	}

	public void setDatiXslMobile(String datiXslMobile) {
		this.datiXslMobile = datiXslMobile;
	}

	public String getHtmlStatico() {
		return this.htmlStatico;
	}

	public void setHtmlStatico(String htmlStatico) {
		this.htmlStatico = htmlStatico;
	}

	public short getFlgAbilitato() {
		return this.flgAbilitato;
	}

	public void setFlgAbilitato(short flgAbilitato) {
		this.flgAbilitato = flgAbilitato;
	}

	public String getIdServizio() {
		return this.idServizio;
	}

	public void setIdServizio(String idServizio) {
		this.idServizio = idServizio;
	}

	public String getUrlServizio() {
		return this.urlServizio;
	}

	public void setUrlServizio(String urlServizio) {
		this.urlServizio = urlServizio;
	}

	public String getNomeServizio() {
		return this.nomeServizio;
	}

	public void setNomeServizio(String nomeServizio) {
		this.nomeServizio = nomeServizio;
	}

	public String getUsernameServizio() {
		return this.usernameServizio;
	}

	public void setUsernameServizio(String usernameServizio) {
		this.usernameServizio = usernameServizio;
	}

	public String getPasswordeServizio() {
		return this.passwordeServizio;
	}

	public void setPasswordeServizio(String passwordeServizio) {
		this.passwordeServizio = passwordeServizio;
	}

	public Set<ParametroServizio> getParametroServizios() {
		return this.parametroServizios;
	}

	public void setParametroServizios(Set<ParametroServizio> parametroServizios) {
		this.parametroServizios = parametroServizios;
	}

	public String getPortletAbilitate() {
		return portletAbilitate;
	}

	public void setPortletAbilitate(String portletAbilitate) {
		this.portletAbilitate = portletAbilitate;
	}

	public String getRenderingClass() {
		return renderingClass;
	}

	public void setRenderingClass(String renderingClass) {
		this.renderingClass = renderingClass;
	}
	

}
