package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FceAgendaUtenteId generated by hbm2java
 */
@Embeddable
public class FceAgendaUtenteId implements java.io.Serializable {

	private BigDecimal idAgenda;
	private BigDecimal idUtente;

	public FceAgendaUtenteId() {
	}

	public FceAgendaUtenteId(BigDecimal idAgenda, BigDecimal idUtente) {
		this.idAgenda = idAgenda;
		this.idUtente = idUtente;
	}

	@Column(name = "ID_AGENDA", nullable = false, precision = 38, scale = 0)
	public BigDecimal getIdAgenda() {
		return this.idAgenda;
	}

	public void setIdAgenda(BigDecimal idAgenda) {
		this.idAgenda = idAgenda;
	}

	@Column(name = "ID_UTENTE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getIdUtente() {
		return this.idUtente;
	}

	public void setIdUtente(BigDecimal idUtente) {
		this.idUtente = idUtente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FceAgendaUtenteId))
			return false;
		FceAgendaUtenteId castOther = (FceAgendaUtenteId) other;

		return ((this.getIdAgenda() == castOther.getIdAgenda()) || (this.getIdAgenda() != null && castOther.getIdAgenda() != null && this.getIdAgenda().equals(castOther.getIdAgenda())))
				&& ((this.getIdUtente() == castOther.getIdUtente()) || (this.getIdUtente() != null && castOther.getIdUtente() != null && this.getIdUtente().equals(castOther.getIdUtente())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdAgenda() == null ? 0 : this.getIdAgenda().hashCode());
		result = 37 * result + (getIdUtente() == null ? 0 : this.getIdUtente().hashCode());
		return result;
	}

}
