package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FceAgendaUtente generated by hbm2java
 */
@Entity
@Table(name = "FCE_AGENDA_UTENTE")
public class FceAgendaUtente implements java.io.Serializable {

	private FceAgendaUtenteId id;
	private String flagPreferito;

	public FceAgendaUtente() {
	}

	public FceAgendaUtente(FceAgendaUtenteId id, String flagPreferito) {
		this.id = id;
		this.flagPreferito = flagPreferito;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idAgenda", column = @Column(name = "ID_AGENDA", nullable = false, precision = 38, scale = 0)), @AttributeOverride(name = "idUtente", column = @Column(name = "ID_UTENTE", nullable = false, precision = 38, scale = 0)) })
	public FceAgendaUtenteId getId() {
		return this.id;
	}

	public void setId(FceAgendaUtenteId id) {
		this.id = id;
	}

	@Column(name = "FLAG_PREFERITO", nullable = false, length = 1)
	public String getFlagPreferito() {
		return this.flagPreferito;
	}

	public void setFlagPreferito(String flagPreferito) {
		this.flagPreferito = flagPreferito;
	}

}
