package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FceAgendaCategoria generated by hbm2java
 */
@Entity
@Table(name = "FCE_AGENDA_CATEGORIA")
public class FceAgendaCategoria implements java.io.Serializable {

	private BigDecimal idagendacategoria;
	private String nome;
	private String hexcolore;
	private String flagPreferito;
	private Set<FceAgenda> fceAgendas = new HashSet<FceAgenda>(0);

	public FceAgendaCategoria() {
	}

	public FceAgendaCategoria(BigDecimal idagendacategoria, String nome, String hexcolore, String flagPreferito) {
		this.idagendacategoria = idagendacategoria;
		this.nome = nome;
		this.hexcolore = hexcolore;
		this.flagPreferito = flagPreferito;
	}

	public FceAgendaCategoria(BigDecimal idagendacategoria, String nome, String hexcolore, String flagPreferito, Set<FceAgenda> fceAgendas) {
		this.idagendacategoria = idagendacategoria;
		this.nome = nome;
		this.hexcolore = hexcolore;
		this.flagPreferito = flagPreferito;
		this.fceAgendas = fceAgendas;
	}

	@Id
	@Column(name = "IDAGENDACATEGORIA", unique = true, nullable = false, precision = 10)
	public BigDecimal getIdagendacategoria() {
		return this.idagendacategoria;
	}

	public void setIdagendacategoria(BigDecimal idagendacategoria) {
		this.idagendacategoria = idagendacategoria;
	}

	@Column(name = "NOME", nullable = false, length = 20)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "HEXCOLORE", nullable = false, length = 20)
	public String getHexcolore() {
		return this.hexcolore;
	}

	public void setHexcolore(String hexcolore) {
		this.hexcolore = hexcolore;
	}

	@Column(name = "FLAG_PREFERITO", nullable = false, length = 1)
	public String getFlagPreferito() {
		return this.flagPreferito;
	}

	public void setFlagPreferito(String flagPreferito) {
		this.flagPreferito = flagPreferito;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fceAgendaCategoria")
	public Set<FceAgenda> getFceAgendas() {
		return this.fceAgendas;
	}

	public void setFceAgendas(Set<FceAgenda> fceAgendas) {
		this.fceAgendas = fceAgendas;
	}

}
