package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FceAgendaSorgenti generated by hbm2java
 */
@Entity
@Table(name = "FCE_AGENDA_SORGENTI")
public class FceAgendaSorgenti implements java.io.Serializable {

	private BigDecimal idsorgente;
	private String nome;
	private String descrizione;
	private String codiceHtmlColore;
	private Set<FceAgenda> fceAgendas = new HashSet<FceAgenda>(0);

	public FceAgendaSorgenti() {
	}

	public FceAgendaSorgenti(BigDecimal idsorgente) {
		this.idsorgente = idsorgente;
	}

	public FceAgendaSorgenti(BigDecimal idsorgente, String nome, String descrizione, String codiceHtmlColore, Set<FceAgenda> fceAgendas) {
		this.idsorgente = idsorgente;
		this.nome = nome;
		this.descrizione = descrizione;
		this.codiceHtmlColore = codiceHtmlColore;
		this.fceAgendas = fceAgendas;
	}

	@Id
	@Column(name = "IDSORGENTE", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getIdsorgente() {
		return this.idsorgente;
	}

	public void setIdsorgente(BigDecimal idsorgente) {
		this.idsorgente = idsorgente;
	}

	@Column(name = "NOME", length = 200)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "DESCRIZIONE", length = 500)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "CODICE_HTML_COLORE", length = 100)
	public String getCodiceHtmlColore() {
		return this.codiceHtmlColore;
	}

	public void setCodiceHtmlColore(String codiceHtmlColore) {
		this.codiceHtmlColore = codiceHtmlColore;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fceAgendaSorgenti")
	public Set<FceAgenda> getFceAgendas() {
		return this.fceAgendas;
	}

	public void setFceAgendas(Set<FceAgenda> fceAgendas) {
		this.fceAgendas = fceAgendas;
	}

}
