package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FceAgenda generated by hbm2java
 */
@Entity
@Table(name = "FCE_AGENDA")
public class FceAgenda implements java.io.Serializable {

	private BigDecimal idagenda;
	private FceUtente fceUtente;
	private FceAgendaSorgenti fceAgendaSorgenti;
	private FceAgendaCategoria fceAgendaCategoria;
	private Date datacreazione;
	private Date datainizio;
	private Date datafine;
	private String titolo;
	private String descrizione;
	private Character tuttoilgiorno;

	public FceAgenda() {
	}

	public FceAgenda(BigDecimal idagenda) {
		this.idagenda = idagenda;
	}

	public FceAgenda(BigDecimal idagenda, FceUtente fceUtente, FceAgendaSorgenti fceAgendaSorgenti, FceAgendaCategoria fceAgendaCategoria, Date datacreazione, Date datainizio, Date datafine, String titolo, String descrizione, Character tuttoilgiorno) {
		this.idagenda = idagenda;
		this.fceUtente = fceUtente;
		this.fceAgendaSorgenti = fceAgendaSorgenti;
		this.fceAgendaCategoria = fceAgendaCategoria;
		this.datacreazione = datacreazione;
		this.datainizio = datainizio;
		this.datafine = datafine;
		this.titolo = titolo;
		this.descrizione = descrizione;
		this.tuttoilgiorno = tuttoilgiorno;
	}

	@Id
	@Column(name = "IDAGENDA", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getIdagenda() {
		return this.idagenda;
	}

	public void setIdagenda(BigDecimal idagenda) {
		this.idagenda = idagenda;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDUTENTE")
	public FceUtente getFceUtente() {
		return this.fceUtente;
	}

	public void setFceUtente(FceUtente fceUtente) {
		this.fceUtente = fceUtente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDSORGENTE")
	public FceAgendaSorgenti getFceAgendaSorgenti() {
		return this.fceAgendaSorgenti;
	}

	public void setFceAgendaSorgenti(FceAgendaSorgenti fceAgendaSorgenti) {
		this.fceAgendaSorgenti = fceAgendaSorgenti;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDAGENDACATEGORIA")
	public FceAgendaCategoria getFceAgendaCategoria() {
		return this.fceAgendaCategoria;
	}

	public void setFceAgendaCategoria(FceAgendaCategoria fceAgendaCategoria) {
		this.fceAgendaCategoria = fceAgendaCategoria;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATACREAZIONE", length = 7)
	public Date getDatacreazione() {
		return this.datacreazione;
	}

	public void setDatacreazione(Date datacreazione) {
		this.datacreazione = datacreazione;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATAINIZIO", length = 7)
	public Date getDatainizio() {
		return this.datainizio;
	}

	public void setDatainizio(Date datainizio) {
		this.datainizio = datainizio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATAFINE", length = 7)
	public Date getDatafine() {
		return this.datafine;
	}

	public void setDatafine(Date datafine) {
		this.datafine = datafine;
	}

	@Column(name = "TITOLO", length = 100)
	public String getTitolo() {
		return this.titolo;
	}

	public void setTitolo(String titolo) {
		this.titolo = titolo;
	}

	@Column(name = "DESCRIZIONE", length = 500)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "TUTTOILGIORNO", length = 1)
	public Character getTuttoilgiorno() {
		return this.tuttoilgiorno;
	}

	public void setTuttoilgiorno(Character tuttoilgiorno) {
		this.tuttoilgiorno = tuttoilgiorno;
	}

}
