package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FceComuni generated by hbm2java
 */
@Entity
@Table(name = "FCE_COMUNI")
public class FceComuni implements java.io.Serializable {

	private String codcomune;
	private FceProvince fceProvince;
	private String descrizione;
	private String codistat;
	private String codinps;
	private String capdefault;
	private String flagcomunestatoestero;
	private String flagvalido;
	private Set<FceUtente> fceUtentesForDomicilioIdComune = new HashSet<FceUtente>(0);
	private Set<FceUtente> fceUtentesForNascitaIdComune = new HashSet<FceUtente>(0);
	private Set<FceUtente> fceUtentesForResidenzaIdComune = new HashSet<FceUtente>(0);

	public FceComuni() {
	}

	public FceComuni(String codcomune, String flagvalido) {
		this.codcomune = codcomune;
		this.flagvalido = flagvalido;
	}

	public FceComuni(String codcomune, FceProvince fceProvince, String descrizione, String codistat, String codinps, String capdefault, String flagcomunestatoestero, String flagvalido, Set<FceUtente> fceUtentesForDomicilioIdComune, Set<FceUtente> fceUtentesForNascitaIdComune,
			Set<FceUtente> fceUtentesForResidenzaIdComune) {
		this.codcomune = codcomune;
		this.fceProvince = fceProvince;
		this.descrizione = descrizione;
		this.codistat = codistat;
		this.codinps = codinps;
		this.capdefault = capdefault;
		this.flagcomunestatoestero = flagcomunestatoestero;
		this.flagvalido = flagvalido;
		this.fceUtentesForDomicilioIdComune = fceUtentesForDomicilioIdComune;
		this.fceUtentesForNascitaIdComune = fceUtentesForNascitaIdComune;
		this.fceUtentesForResidenzaIdComune = fceUtentesForResidenzaIdComune;
	}

	@Id
	@Column(name = "CODCOMUNE", unique = true, nullable = false, length = 11)
	public String getCodcomune() {
		return this.codcomune;
	}

	public void setCodcomune(String codcomune) {
		this.codcomune = codcomune;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODPROVINCIA")
	public FceProvince getFceProvince() {
		return this.fceProvince;
	}

	public void setFceProvince(FceProvince fceProvince) {
		this.fceProvince = fceProvince;
	}

	@Column(name = "DESCRIZIONE", length = 100)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "CODISTAT", length = 8)
	public String getCodistat() {
		return this.codistat;
	}

	public void setCodistat(String codistat) {
		this.codistat = codistat;
	}

	@Column(name = "CODINPS", length = 4)
	public String getCodinps() {
		return this.codinps;
	}

	public void setCodinps(String codinps) {
		this.codinps = codinps;
	}

	@Column(name = "CAPDEFAULT", length = 5)
	public String getCapdefault() {
		return this.capdefault;
	}

	public void setCapdefault(String capdefault) {
		this.capdefault = capdefault;
	}

	@Column(name = "FLAGCOMUNESTATOESTERO", length = 1)
	public String getFlagcomunestatoestero() {
		return this.flagcomunestatoestero;
	}

	public void setFlagcomunestatoestero(String flagcomunestatoestero) {
		this.flagcomunestatoestero = flagcomunestatoestero;
	}

	@Column(name = "FLAGVALIDO", nullable = false, length = 1)
	public String getFlagvalido() {
		return this.flagvalido;
	}

	public void setFlagvalido(String flagvalido) {
		this.flagvalido = flagvalido;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fceComuniByDomicilioIdComune")
	public Set<FceUtente> getFceUtentesForDomicilioIdComune() {
		return this.fceUtentesForDomicilioIdComune;
	}

	public void setFceUtentesForDomicilioIdComune(Set<FceUtente> fceUtentesForDomicilioIdComune) {
		this.fceUtentesForDomicilioIdComune = fceUtentesForDomicilioIdComune;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fceComuniByNascitaIdComune")
	public Set<FceUtente> getFceUtentesForNascitaIdComune() {
		return this.fceUtentesForNascitaIdComune;
	}

	public void setFceUtentesForNascitaIdComune(Set<FceUtente> fceUtentesForNascitaIdComune) {
		this.fceUtentesForNascitaIdComune = fceUtentesForNascitaIdComune;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fceComuniByResidenzaIdComune")
	public Set<FceUtente> getFceUtentesForResidenzaIdComune() {
		return this.fceUtentesForResidenzaIdComune;
	}

	public void setFceUtentesForResidenzaIdComune(Set<FceUtente> fceUtentesForResidenzaIdComune) {
		this.fceUtentesForResidenzaIdComune = fceUtentesForResidenzaIdComune;
	}

}
