package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * FceInteresse generated by hbm2java
 */
@Entity
@Table(name = "FCE_INTERESSE", uniqueConstraints = @UniqueConstraint(columnNames = "DESCRIZIONE"))
public class FceInteresse implements java.io.Serializable {

	private BigDecimal idInteresse;
	private String descrizione;
	private Set<FceUtente> fceUtentes = new HashSet<FceUtente>(0);

	public FceInteresse() {
	}

	public FceInteresse(BigDecimal idInteresse, String descrizione) {
		this.idInteresse = idInteresse;
		this.descrizione = descrizione;
	}

	public FceInteresse(BigDecimal idInteresse, String descrizione, Set<FceUtente> fceUtentes) {
		this.idInteresse = idInteresse;
		this.descrizione = descrizione;
		this.fceUtentes = fceUtentes;
	}

	@Id
	@Column(name = "ID_INTERESSE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdInteresse() {
		return this.idInteresse;
	}

	public void setIdInteresse(BigDecimal idInteresse) {
		this.idInteresse = idInteresse;
	}

	@Column(name = "DESCRIZIONE", unique = true, nullable = false, length = 200)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "FCE_UTENTE_INTERESSE", joinColumns = { @JoinColumn(name = "ID_INTERESSE", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ID_UTENTE", nullable = false, updatable = false) })
	public Set<FceUtente> getFceUtentes() {
		return this.fceUtentes;
	}

	public void setFceUtentes(Set<FceUtente> fceUtentes) {
		this.fceUtentes = fceUtentes;
	}

}
