package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FceIntornoameKmlCat generated by hbm2java
 */
@Entity
@Table(name = "FCE_INTORNOAME_KML_CAT")
public class FceIntornoameKmlCat implements java.io.Serializable {

	private FceIntornoameKmlCatId id;
	private FceIntornoameCategoria fceIntornoameCategoria;
	private FceIntornoameKml fceIntornoameKml;

	public FceIntornoameKmlCat() {
	}

	public FceIntornoameKmlCat(FceIntornoameKmlCatId id, FceIntornoameCategoria fceIntornoameCategoria, FceIntornoameKml fceIntornoameKml) {
		this.id = id;
		this.fceIntornoameCategoria = fceIntornoameCategoria;
		this.fceIntornoameKml = fceIntornoameKml;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idkml", column = @Column(name = "IDKML", nullable = false, precision = 38, scale = 0)), @AttributeOverride(name = "idcategoria", column = @Column(name = "IDCATEGORIA", nullable = false, precision = 38, scale = 0)) })
	public FceIntornoameKmlCatId getId() {
		return this.id;
	}

	public void setId(FceIntornoameKmlCatId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCATEGORIA", nullable = false, insertable = false, updatable = false)
	public FceIntornoameCategoria getFceIntornoameCategoria() {
		return this.fceIntornoameCategoria;
	}

	public void setFceIntornoameCategoria(FceIntornoameCategoria fceIntornoameCategoria) {
		this.fceIntornoameCategoria = fceIntornoameCategoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDKML", nullable = false, insertable = false, updatable = false)
	public FceIntornoameKml getFceIntornoameKml() {
		return this.fceIntornoameKml;
	}

	public void setFceIntornoameKml(FceIntornoameKml fceIntornoameKml) {
		this.fceIntornoameKml = fceIntornoameKml;
	}

}
