package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FceIntornoameCategoria generated by hbm2java
 */
@Entity
@Table(name = "FCE_INTORNOAME_CATEGORIA")
public class FceIntornoameCategoria implements java.io.Serializable {

	private BigDecimal idcategoria;
	private String descrizione;
	private char flagAttivo;
	private Set<FceIntornoameKmlCat> fceIntornoameKmlCats = new HashSet<FceIntornoameKmlCat>(0);

	public FceIntornoameCategoria() {
	}

	public FceIntornoameCategoria(BigDecimal idcategoria, char flagAttivo) {
		this.idcategoria = idcategoria;
		this.flagAttivo = flagAttivo;
	}

	public FceIntornoameCategoria(BigDecimal idcategoria, String descrizione, char flagAttivo, Set<FceIntornoameKmlCat> fceIntornoameKmlCats) {
		this.idcategoria = idcategoria;
		this.descrizione = descrizione;
		this.flagAttivo = flagAttivo;
		this.fceIntornoameKmlCats = fceIntornoameKmlCats;
	}

	@Id
	@Column(name = "IDCATEGORIA", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(BigDecimal idcategoria) {
		this.idcategoria = idcategoria;
	}

	@Column(name = "DESCRIZIONE", length = 200)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "FLAG_ATTIVO", nullable = false, length = 1)
	public char getFlagAttivo() {
		return this.flagAttivo;
	}

	public void setFlagAttivo(char flagAttivo) {
		this.flagAttivo = flagAttivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fceIntornoameCategoria")
	public Set<FceIntornoameKmlCat> getFceIntornoameKmlCats() {
		return this.fceIntornoameKmlCats;
	}

	public void setFceIntornoameKmlCats(Set<FceIntornoameKmlCat> fceIntornoameKmlCats) {
		this.fceIntornoameKmlCats = fceIntornoameKmlCats;
	}

}
