package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FceIntornoameKmlCatId generated by hbm2java
 */
@Embeddable
public class FceIntornoameKmlCatId implements java.io.Serializable {

	private BigDecimal idkml;
	private BigDecimal idcategoria;

	public FceIntornoameKmlCatId() {
	}

	public FceIntornoameKmlCatId(BigDecimal idkml, BigDecimal idcategoria) {
		this.idkml = idkml;
		this.idcategoria = idcategoria;
	}

	@Column(name = "IDKML", nullable = false, precision = 38, scale = 0)
	public BigDecimal getIdkml() {
		return this.idkml;
	}

	public void setIdkml(BigDecimal idkml) {
		this.idkml = idkml;
	}

	@Column(name = "IDCATEGORIA", nullable = false, precision = 38, scale = 0)
	public BigDecimal getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(BigDecimal idcategoria) {
		this.idcategoria = idcategoria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FceIntornoameKmlCatId))
			return false;
		FceIntornoameKmlCatId castOther = (FceIntornoameKmlCatId) other;

		return ((this.getIdkml() == castOther.getIdkml()) || (this.getIdkml() != null && castOther.getIdkml() != null && this.getIdkml().equals(castOther.getIdkml())))
				&& ((this.getIdcategoria() == castOther.getIdcategoria()) || (this.getIdcategoria() != null && castOther.getIdcategoria() != null && this.getIdcategoria().equals(castOther.getIdcategoria())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdkml() == null ? 0 : this.getIdkml().hashCode());
		result = 37 * result + (getIdcategoria() == null ? 0 : this.getIdcategoria().hashCode());
		return result;
	}

}
