package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FceIntornoameKmlUtente generated by hbm2java
 */
@Entity
@Table(name = "FCE_INTORNOAME_KML_UTENTE")
public class FceIntornoameKmlUtente implements java.io.Serializable {

	private FceIntornoameKmlUtenteId id;
	private FceIntornoameKml fceIntornoameKml;

	public FceIntornoameKmlUtente() {
	}

	public FceIntornoameKmlUtente(FceIntornoameKmlUtenteId id, FceIntornoameKml fceIntornoameKml) {
		this.id = id;
		this.fceIntornoameKml = fceIntornoameKml;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idkml", column = @Column(name = "IDKML", nullable = false, precision = 38, scale = 0)), @AttributeOverride(name = "idutente", column = @Column(name = "IDUTENTE", nullable = false, precision = 38, scale = 0)) })
	public FceIntornoameKmlUtenteId getId() {
		return this.id;
	}

	public void setId(FceIntornoameKmlUtenteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDKML", nullable = false, insertable = false, updatable = false)
	public FceIntornoameKml getFceIntornoameKml() {
		return this.fceIntornoameKml;
	}

	public void setFceIntornoameKml(FceIntornoameKml fceIntornoameKml) {
		this.fceIntornoameKml = fceIntornoameKml;
	}

}
