package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FceIntornoameKml generated by hbm2java
 */
@Entity
@Table(name = "FCE_INTORNOAME_KML")
public class FceIntornoameKml implements java.io.Serializable {

	private BigDecimal idkml;
	private String kmlurl;
	private Clob kmlfile;
	private String titolo;
	private Date lastupdate;
	private char flagAttivo;
	private String kmlIconUrl;
	private Set<FceIntornoameKmlUtente> fceIntornoameKmlUtentes = new HashSet<FceIntornoameKmlUtente>(0);
	private Set<FceIntornoameKmlCat> fceIntornoameKmlCats = new HashSet<FceIntornoameKmlCat>(0);

	public FceIntornoameKml() {
	}

	public FceIntornoameKml(BigDecimal idkml, char flagAttivo) {
		this.idkml = idkml;
		this.flagAttivo = flagAttivo;
	}

	public FceIntornoameKml(BigDecimal idkml, String kmlurl, Clob kmlfile, String titolo, Date lastupdate, char flagAttivo, String kmlIconUrl, Set<FceIntornoameKmlUtente> fceIntornoameKmlUtentes, Set<FceIntornoameKmlCat> fceIntornoameKmlCats) {
		this.idkml = idkml;
		this.kmlurl = kmlurl;
		this.kmlfile = kmlfile;
		this.titolo = titolo;
		this.lastupdate = lastupdate;
		this.flagAttivo = flagAttivo;
		this.kmlIconUrl = kmlIconUrl;
		this.fceIntornoameKmlUtentes = fceIntornoameKmlUtentes;
		this.fceIntornoameKmlCats = fceIntornoameKmlCats;
	}

	@Id
	@Column(name = "IDKML", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getIdkml() {
		return this.idkml;
	}

	public void setIdkml(BigDecimal idkml) {
		this.idkml = idkml;
	}

	@Column(name = "KMLURL", length = 200)
	public String getKmlurl() {
		return this.kmlurl;
	}

	public void setKmlurl(String kmlurl) {
		this.kmlurl = kmlurl;
	}

	@Column(name = "KMLFILE")
	public Clob getKmlfile() {
		return this.kmlfile;
	}

	public void setKmlfile(Clob kmlfile) {
		this.kmlfile = kmlfile;
	}

	@Column(name = "TITOLO", length = 200)
	public String getTitolo() {
		return this.titolo;
	}

	public void setTitolo(String titolo) {
		this.titolo = titolo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LASTUPDATE", length = 7)
	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	@Column(name = "FLAG_ATTIVO", nullable = false, length = 1)
	public char getFlagAttivo() {
		return this.flagAttivo;
	}

	public void setFlagAttivo(char flagAttivo) {
		this.flagAttivo = flagAttivo;
	}

	@Column(name = "KML_ICON_URL", length = 200)
	public String getKmlIconUrl() {
		return this.kmlIconUrl;
	}

	public void setKmlIconUrl(String kmlIconUrl) {
		this.kmlIconUrl = kmlIconUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fceIntornoameKml")
	public Set<FceIntornoameKmlUtente> getFceIntornoameKmlUtentes() {
		return this.fceIntornoameKmlUtentes;
	}

	public void setFceIntornoameKmlUtentes(Set<FceIntornoameKmlUtente> fceIntornoameKmlUtentes) {
		this.fceIntornoameKmlUtentes = fceIntornoameKmlUtentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fceIntornoameKml")
	public Set<FceIntornoameKmlCat> getFceIntornoameKmlCats() {
		return this.fceIntornoameKmlCats;
	}

	public void setFceIntornoameKmlCats(Set<FceIntornoameKmlCat> fceIntornoameKmlCats) {
		this.fceIntornoameKmlCats = fceIntornoameKmlCats;
	}

}
