package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * FceProvince generated by hbm2java
 */
@Entity
@Table(name = "FCE_PROVINCE", uniqueConstraints = @UniqueConstraint(columnNames = "STRTARGA"))
public class FceProvince implements java.io.Serializable {

	private String codprovincia;
	private String descrizione;
	private String strtarga;
	private String stristat;
	private String codregione;
	private String flagvalido;
	private BigDecimal posizione;
	private Set<FceComuni> fceComunis = new HashSet<FceComuni>(0);

	public FceProvince() {
	}

	public FceProvince(String codprovincia, String flagvalido) {
		this.codprovincia = codprovincia;
		this.flagvalido = flagvalido;
	}

	public FceProvince(String codprovincia, String descrizione, String strtarga, String stristat, String codregione, String flagvalido, BigDecimal posizione, Set<FceComuni> fceComunis) {
		this.codprovincia = codprovincia;
		this.descrizione = descrizione;
		this.strtarga = strtarga;
		this.stristat = stristat;
		this.codregione = codregione;
		this.flagvalido = flagvalido;
		this.posizione = posizione;
		this.fceComunis = fceComunis;
	}

	@Id
	@Column(name = "CODPROVINCIA", unique = true, nullable = false, length = 4)
	public String getCodprovincia() {
		return this.codprovincia;
	}

	public void setCodprovincia(String codprovincia) {
		this.codprovincia = codprovincia;
	}

	@Column(name = "DESCRIZIONE", length = 100)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "STRTARGA", unique = true, length = 2)
	public String getStrtarga() {
		return this.strtarga;
	}

	public void setStrtarga(String strtarga) {
		this.strtarga = strtarga;
	}

	@Column(name = "STRISTAT", length = 2)
	public String getStristat() {
		return this.stristat;
	}

	public void setStristat(String stristat) {
		this.stristat = stristat;
	}

	@Column(name = "CODREGIONE", length = 4)
	public String getCodregione() {
		return this.codregione;
	}

	public void setCodregione(String codregione) {
		this.codregione = codregione;
	}

	@Column(name = "FLAGVALIDO", nullable = false, length = 1)
	public String getFlagvalido() {
		return this.flagvalido;
	}

	public void setFlagvalido(String flagvalido) {
		this.flagvalido = flagvalido;
	}

	@Column(name = "POSIZIONE", precision = 38, scale = 0)
	public BigDecimal getPosizione() {
		return this.posizione;
	}

	public void setPosizione(BigDecimal posizione) {
		this.posizione = posizione;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fceProvince")
	public Set<FceComuni> getFceComunis() {
		return this.fceComunis;
	}

	public void setFceComunis(Set<FceComuni> fceComunis) {
		this.fceComunis = fceComunis;
	}

}
