package it.eng.fascicolo.commons.jpa.model;

// Generated Dec 5, 2014 12:35:56 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FceStatoNewsletter generated by hbm2java
 */
@Entity
@Table(name = "FCE_STATO_NEWSLETTER")
public class FceStatoNewsletter implements java.io.Serializable {

	private BigDecimal idstato;
	private String descrizione;
	private Set<FceUtente> fceUtentes = new HashSet<FceUtente>(0);

	public FceStatoNewsletter() {
	}

	public FceStatoNewsletter(BigDecimal idstato) {
		this.idstato = idstato;
	}

	public FceStatoNewsletter(BigDecimal idstato, String descrizione, Set<FceUtente> fceUtentes) {
		this.idstato = idstato;
		this.descrizione = descrizione;
		this.fceUtentes = fceUtentes;
	}

	@Id
	@Column(name = "IDSTATO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdstato() {
		return this.idstato;
	}

	public void setIdstato(BigDecimal idstato) {
		this.idstato = idstato;
	}

	@Column(name = "DESCRIZIONE", length = 200)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fceStatoNewsletter")
	public Set<FceUtente> getFceUtentes() {
		return this.fceUtentes;
	}

	public void setFceUtentes(Set<FceUtente> fceUtentes) {
		this.fceUtentes = fceUtentes;
	}

}
